name: gh-pages
on: [push, pull_request]
jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn
      - name: Run setup script
        run: yarn run setup
  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run lint (ESLint)
        run: yarn run lint
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run Test (Jest)
        run: yarn run test
  publish:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Generate
        run: yarn run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
